/*****************************************************************************
*  Copyright (c) 2021 BJTU, Inc.
*  Licensed under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License.
*  You may obtain a copy of the License at
*      http://www.apache.org/licenses/LICENSE-2.0
*  Unless required by applicable law or agreed to in writing, software
*  distributed under the License is distributed outlookon an "AS IS" BASIS,
*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*  See the License for the specific language governing permissions and
*  limitations under the License.
*  Authors: Shawntao (shawntao-cn@outlook.com)
*  Date: 2021-12-04
*******************************************************************************/

#ifndef DETECT_TASK_H
#define DETECT_TASK_H

#include <QObject>
#include <QString>
#include <QQueue>

enum MSGTYPE{
    ACTIVATE_MSG= 0,
    FILE_MSG,
    END_MSG,
};

class Detect_Message : public QObject
{
    Q_OBJECT
public:
    // name of message length is not fixed
    QString message_name;

    // type of message, there are three type in this program, stipulated by MSGTYPE
    QString message_type;

    // if is a file msg, there are file path
    QString file_path;
    bool if_sended = false;

public:
    explicit Detect_Message(QObject *parent = 0);
    bool send_str();
    bool send_file();

};

class Detect_Task : public QObject
{
    Q_OBJECT
public:
    // Name of task generated by time
    QString task_name;
    // Config of task given by andriod
    QString task_conf;
    // Path of task(the config file was build in this path)
    QString task_path;

    Detect_Message Start_msg;

    Detect_Message end_msg;

    QQueue<Detect_Message> file_msg_q;

public:
    explicit Detect_Task(QObject *parent = 0);
    bool start_detect();
    bool stop_detect();
};

#endif // DETECT_TASK_H
