#ifndef DETECT_TASK_H
#define DETECT_TASK_H

#include <QObject>
#include <QString>
#include <QQueue>

enum MSGTYPE{
    ACTIVATE_MSG= 0,
    FILE_MSG,
    END_MSG,
};

class Detect_Message : public QObject
{
    Q_OBJECT
public:
    // name of message length is not fixed
    QString message_name;

    // type of message, there are three type in this program, stipulated by MSGTYPE
    QString message_type;

    // if is a file msg, there are file path
    QString file_path;
    bool if_sended = false;

public:
    explicit Detect_Message(QObject *parent = 0);
    bool send_str();
    bool send_file();

};



class Detect_Task : public QObject
{
    Q_OBJECT
public:
    // Name of task generated by time
    QString task_name;
    // Config of task given by andriod
    QString task_conf;
    // Path of task(the config file was build in this path)
    QString task_path;

    Detect_Message Start_msg;

    Detect_Message end_msg;

    QQueue<Detect_Message> file_msg_q;

public:
    explicit Detect_Task(QObject *parent = 0);
    bool start_detect();
    bool stop_detect();
};

#endif // DETECT_TASK_H
